[project]
name = "data-hub-lambda"
version = "0.0.0"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Arcadia Science", email = "swe@arcadiascience.com" },
]
dependencies = [
    "data-hub-shared",
    "arcadia-microscopy-tools>=0.4.1",
    "aws-lambda-typing>=2.20.0",
    "click>=8.1",
    "matplotlib>=3.8",
    "pandas>=2.2",
    "pydantic>=2.11.9",
    "requests>=2.31.0",
    "tifffile>=2025.9.30",
    "scikit-image>=0.26.0",
    "openpyxl>=3.1.5",
]

[project.scripts]
data-hub-process = "data_hub_lambda.cli:cli"

[build-system]
requires = ["setuptools>=77.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
data-hub-shared = { workspace = true }

[tool.setuptools.packages.find]
where = ["src"]
