[project]
name = "data-hub-lambda"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = [
    "data-hub-shared",
    "aws-lambda-typing>=2.20.0",
    "matplotlib>=3.8",
    "pandas>=2.2",
    "pydantic>=2.11.9",
    "requests>=2.31.0",
    "tifffile>=2025.9.30",
    "scikit-image>=0.26.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
data-hub-shared = { workspace = true }

[tool.setuptools.packages.find]
where = ["src"]
