name: Lint and typecheck web app

on:
  push:
    branches:
      - staging
      - production
  pull_request:
    branches:
      - staging
      - production

defaults:
  run:
    working-directory: web-app

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck