import { auth } from "@/lib/auth";
import { NextResponse } from "next/server";

// Routes whose page bodies must be reachable without a session so that link
// unfurlers (Slack, Notion, etc.) and signed-out humans can read the page
// metadata. The page (or layout) renders a `SignInRequired` CTA in place
// of the real body when there's no session, so no data ever leaks; the
// metadata exports still resolve and produce a useful unfurl.
//
// Each entry matches its exact path or any descendant under it. The trailing
// `/` boundary in the descendant check is what stops `/api/v1` from also
// matching `/api/v1foo` (or `/login` from matching `/loginz`, etc.).
const publicPrefixes = [
  "/login",
  "/api/auth",
  "/api/v1",
  "/instruments",
  "/settings",
];

// Paths that are public for the index URL only — descendants stay
// proxy-gated. The root dashboard is here because adding `/` to
// `publicPrefixes` would match every path. `/watchers` is exact-only so
// the index page renders metadata for link unfurls while `/watchers/[id]`
// stays proxy-gated (those URLs aren't shared externally and the detail
// page surfaces watcher config YAML / hostnames).
const publicExactPaths = new Set(["/", "/watchers"]);

export const proxy = auth((req) => {
  const { pathname } = req.nextUrl;

  const isPublic =
    publicExactPaths.has(pathname) ||
    publicPrefixes.some(
      (route) => pathname === route || pathname.startsWith(`${route}/`)
    );
  if (isPublic) {
    return NextResponse.next();
  }

  if (!req.auth) {
    const loginUrl = new URL("/login", req.url);
    return NextResponse.redirect(loginUrl);
  }

  return NextResponse.next();
});

export const config = {
  // Paths excluded from the matcher entirely (middleware never runs):
  //
  //   - `_next/static`, `_next/image` — Next-internal asset URLs.
  //   - `favicon.ico` — legacy favicon.
  //   - `images/` — static assets under `public/images/`, including the
  //     site logo used as `og:image`.
  //   - `robots.txt`, `sitemap.xml` — generated by `app/robots.ts` /
  //     `app/sitemap.ts`; must be reachable for crawlers and unfurlers.
  //   - `icon.<ext>`, `apple-icon.<ext>`, `opengraph-image.<ext>`,
  //     `twitter-image.<ext>` — Next.js metadata file conventions
  //     (`app/icon.svg`, etc.). These are referenced from `<head>` and
  //     fetched by unfurlers and browsers without a session, so
  //     redirecting them to `/login` breaks favicons and OG images.
  //
  // Excluding instead of allow-listing also avoids running `auth()` +
  // a DB lookup on every asset fetch.
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|images/|robots.txt|sitemap.xml|icon\\..+|apple-icon\\..+|opengraph-image\\..+|twitter-image\\..+).*)",
  ],
};
