import { getSessionCookie } from "better-auth/cookies";
import { type NextRequest, NextResponse } from "next/server";

// Routes whose page bodies must be reachable without a session so that link
// unfurlers (Slack, Notion, etc.) and signed-out humans can read the page
// metadata. The page (or layout) renders a `SignInRequired` CTA in place
// of the real body when there's no session, so no data ever leaks; the
// metadata exports still resolve and produce a useful unfurl.
//
// Each entry matches its exact path or any descendant under it. The trailing
// `/` boundary in the descendant check is what stops `/api/v1` from also
// matching `/api/v1foo` (or `/login` from matching `/loginz`, etc.).
const publicPrefixes = [
  "/login",
  // OAuth consent UI — reachable mid-authorize before a session exists
  // (the page itself redirects to `/login` when unsigned).
  "/consent",
  "/api/auth",
  "/api/v1",
  // MCP authenticates via OAuth (or flagged PAT fallback), never a
  // session cookie — a redirect to `/login` would surface as opaque HTML
  // instead of a 401 + WWW-Authenticate challenge.
  "/mcp",
  // RFC 8414 / 9728 discovery documents for MCP OAuth clients.
  "/.well-known",
  // Cron jobs (e.g. the upload-queue sweep) are invoked by Vercel Cron with no
  // user session — they authenticate themselves via `CRON_SECRET`. Without
  // this, the middleware redirects them to `/login` and the job never runs.
  "/api/cron",
  "/instruments",
  "/settings",
];

// Paths that are public for the index URL only — descendants stay
// proxy-gated. The root dashboard is here because adding `/` to
// `publicPrefixes` would match every path. `/watchers` is exact-only so
// the index page renders metadata for link unfurls while `/watchers/[id]`
// stays proxy-gated (those URLs aren't shared externally and the detail
// page surfaces watcher config YAML / hostnames).
const publicExactPaths = new Set(["/", "/watchers"]);

export function proxy(request: NextRequest) {
  const { pathname } = request.nextUrl;

  const isPublic =
    publicExactPaths.has(pathname) ||
    publicPrefixes.some(
      (route) => pathname === route || pathname.startsWith(`${route}/`)
    );
  if (isPublic) {
    return NextResponse.next();
  }

  // Cookie presence only — optimistic redirect. Pages still call `auth()`
  // / `SignInRequired` for the real session check.
  const sessionCookie = getSessionCookie(request);
  if (!sessionCookie) {
    const loginUrl = new URL("/login", request.url);
    return NextResponse.redirect(loginUrl);
  }

  return NextResponse.next();
}

export const config = {
  // Paths excluded from the matcher entirely (middleware never runs):
  //
  //   - `_next/static`, `_next/image` — Next-internal asset URLs.
  //   - `favicon.ico` — legacy favicon.
  //   - `images/` — static assets under `public/images/`, including the
  //     site logo used as `og:image`.
  //   - `robots.txt`, `sitemap.xml` — generated by `app/robots.ts` /
  //     `app/sitemap.ts`; must be reachable for crawlers and unfurlers.
  //   - `icon`, `apple-icon`, `opengraph-image`, `twitter-image` — Next.js
  //     metadata routes (`app/icon.svg`, etc.). Next serves these at the
  //     EXTENSIONLESS path with a cache-busting query (`/icon?<hash>`), not
  //     `/icon.svg` — so the exclusion must be the bare prefix. Matching
  //     `icon\..+` missed `/icon`, which redirected unfurlers/browsers to
  //     `/login` and broke the favicon and OG images on link previews.
  //
  // Excluding instead of allow-listing also avoids running auth checks on
  // every asset fetch.
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|images/|robots.txt|sitemap.xml|icon|apple-icon|opengraph-image|twitter-image).*)",
  ],
};
